name: WDIO-CI

on:
  push:
    branches:
      - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
          - name: Checkout code
            uses: actions/checkout@v2

          - name: Install Chromium
            run: sudo apt-get install chromium-browser 
    
          - name: Set up Node.js
            uses: actions/setup-node@v2
            with:
                node-version: '16'
    
          - name: Install dependencies
            run: npm install
    
          - name: Run WebdriverIO tests
            run: npm run wdio